VIRTUAL_WIDTH = 1980 --512
VIRTUAL_HEIGHT = 1080 --288

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

CARD_WIDTH = 80
CARD_HEIGHT = 120

BACKGROUND_SCROLL_SPEED = 50

PHASE_TEXT_GAP = 60

-- circle x pos
FLX = VIRTUAL_WIDTH*3/8 -CARD_WIDTH/2 
BLX = FLX

VX = VIRTUAL_WIDTH/2 - CARD_WIDTH/2 
BCX = VX
GX = VX

FRX = VIRTUAL_WIDTH*5/8 -CARD_WIDTH/2
BRX = FRX

-- circle y pos
FLY = VIRTUAL_HEIGHT*5/8 - CARD_HEIGHT/2
VY = FLY
FRY = FLY

BLY = VIRTUAL_HEIGHT*6/8 - CARD_HEIGHT/2
BCY = BLY
BRY = BLY

GY = VIRTUAL_HEIGHT/2 - CARD_HEIGHT/2
